service: team-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION}
  environment:
    TABLE: ${env:TEAM_TABLE}  
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}

  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:BatchWriteItem
          Resource: 
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TABLE}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TABLE}/index/TeamNameIndex
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TABLE}/index/SK-Index
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TABLE}/index/teamID-Index
      managedPolicies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      assumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
resources:
  Resources:
    TeamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE}        
        AttributeDefinitions:  
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: teamName
            AttributeType: S
          - AttributeName: teamID
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: TeamNameIndex
            KeySchema:
              - AttributeName: teamName
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: SK-Index
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: teamID-Index
            KeySchema:
              - AttributeName: teamID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

package:
  individually: true
  patterns:
    - "!package-lock.json"
    - "package.json" 
    - node_modules/uuid/**
    - node_modules/axios/**
    - "!.env"

functions:
  createTeam:
    handler: service/team-handler.createTeam
    events:
      - http:
          path: /api/teams/new
          method: post
  checkTeamName:
    handler: service/team-handler.checkTeamName
    events:
      - http:
          path: /api/teams/new/{teamName}
          method: get
  getAllTeamSpaces:
    handler: service/team-handler.getAllTeamSpaces
    events:
      - http:
          path: /api/teams
          method: get
  getTeamProfile:
    handler: service/team-handler.getTeamProfile
    events:
      - http:
          path: /api/teams/{teamId}
          method: get
  updateTeam:
    handler: service/team-handler.updateTeam
    events:
      - http:
          path: /api/teams/{teamId}
          method: put
  deleteTeam:
    handler: service/team-handler.deleteTeam
    events:
      - http:
          path: /api/teams/{teamId}
          method: delete
          
plugins:
  - serverless-dotenv-plugin