service: team-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ${env:REGION}
  environment:
    TEAM_TABLE: ${env:TEAM_TABLE}  
    USER_TABLE: ${env:USER_TABLE}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:BatchWriteItem
          Resource: 
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TEAM_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TEAM_TABLE}/index/TeamNameIndex
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TEAM_TABLE}/index/SK-Index
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.TEAM_TABLE}/index/teamID-Index
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'

resources:
  Resources:
    TeamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEAM_TABLE}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: teamName
            AttributeType: S     
          - AttributeName: itemType
            AttributeType: S
       
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: SK-Index
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - teamID
          - IndexName: TeamName-Index
            KeySchema:
              - AttributeName: teamName
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
          - IndexName: ItemType-Index
            KeySchema:
              - AttributeName: PK
                KeyType: HASH
              - AttributeName: itemType
                KeyType: RANGE
            Projection:
              ProjectionType: ALL


functions:
  getTeams:
    handler: src/handlers/teamUserHandler.getTeams
    events:
      - http:
          path: /
          method: get
          cors: true
          # authorizer:
            # type: request
            # identitySource: method.request.header.Authorization

  createTeam:
    handler: src/handlers/teamHandler.createTeam
    events:
      - http:
          path: /
          method: post
          cors: true   
  checkTeamName:
    handler: src/handlers/teamHandler.checkTeamName
    events:
      - http:
          path: /check-name/{teamName}
          method: get
          cors: true
  
  getTeamProfile:
    handler: src/handlers/teamHandler.getTeamProfile
    events:
      - http:
          path: /{teamId}
          method: get
          cors: true
  
  checkTeamUserRole:
    handler: src/handlers/teamUserHandler.checkTeamUserRole
    events:
      - http:
          path: /{teamId}/role
          method: get
          cors: true
  getTeamUsersProfile:
    handler: src/handlers/teamUserHandler.getTeamUsersProfile
    events:
      - http:
          path: /{teamId}/user
          method: get
          cors: true
          # authorizer:
          #   type: request
          #   identitySource: method.request.header.Authorization
  updateTeam:
    handler: src/handlers/teamHandler.updateTeam
    events:
      - http:
          path: /{teamId}/settings/info
          method: put
          cors: true
  deleteTeam:
    handler: src/handlers/teamHandler.deleteTeam
    events:
      - http:
          path: /{teamId}/settings
          method: delete
          cors: true
  updateTeamUsers:
    handler: src/handlers/teamUserHandler.updateTeamUsers
    events:
      - http:
          path: /{teamId}/setting/users
          method: put
          cors: true

plugins:
  - serverless-dotenv-plugin
  # - serverless-domain-manager

package:
  individually: true
  patterns:
    - "!package-lock.json"
    - "package.json" 
    - node_modules/uuid/**
    - node_modules/axios/**
    - "!.env"