service: team-service


provider:
  name: aws
  runtime: nodejs20.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    CLIENT_ID: ${env:CLIENT_ID}

functions:
  testEndpoint:
    handler: service/bookHandler.js
    events:
      - http:
          path: /book/search
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin

package:
  include:
    - package.json
    - node_modules/axios/**
    - src/utils/**
    - src/handler/**
  exclude:
    - package-lock.json
    - .env.dev
    - .env.local
    - .env.prod