service: book-service


provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ${env:REGION}
  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}

functions:
  testEndpoint:
    handler: service/bookHandler.js
    events:
      - http:
          path: 
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - "!package-lock.json"
    - "package.json" 
    - node_modules/axios/**
    - "!.env"