service: community-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION}
  environment:
    DYNAMODB_TABLE: ${env:METADATA_TABLE}
    REGION: ${aws:region}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"

functions:
  createPost:
    handler: service/createPost.handler
    events:
      - httpApi:
          path: /api/community/{boardType}/new
          method: POST
  getPost:
    handler: service/getPost.handler
    events:
      - httpApi:
          path: /api/community/{boardType}/{postId}
          method: GET
  listPosts:
    handler: service/listPosts.handler
    events:
      - httpApi:
          path: /api/community/{boardType}
          method: GET

resources:
  Resources:
    EsquadPostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: boardType
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: BoardIndex
            KeySchema:
              - AttributeName: boardType
                KeyType: HASH
              - AttributeName: SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        SSESpecification:
          SSEEnabled: true

plugins:
  - serverless-dotenv-plugin
