service: analysis-visualization

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  getData:
    handler: src/handlers/analytic.handler
    events:
      - http:
          path: data
          method: get
