name: Deploy-Stream-Front-Develop

on:
  pull_request_target:
    branches:
      - develop
    paths: 'stream-frontend/**'
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stream-frontend
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Source Code.
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./stream-frontend/package-lock.json
      - run: npm --force ci

      - name: Build Production.
        run: CI=false npm run build --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region us-east-1 dist s3://esquad-stream-front-dev --delete

      - name: Invalid CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.STREAM_DEV_AWS_DISTRIBUTION_ID }} --paths "/*"
